# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React-Vite-PR

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
    paths:
      - 'demo/react-vite/**'
      - 'demo/shared/**'
      - 'demo/e2e/**'
      - '.github/workflows/react-vite-pr.yml'
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    defaults:
      run:
        working-directory: demo/react-vite

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Merge master into current branch
        run: |
          git fetch origin master
          git merge origin/master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      # - name: Unit Test
      #   run: npm run test

      - name: Build
        run: npm run build

      - name: EndToEnd Test
        run: cd ../e2e && npm run test:prepare && npm run test:react-vite

      - name: Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.15.x
          cd ../../ && lhci collect --collect.staticDistDir=. --collect.url=http://localhost/demo/react-vite/dist --upload.target=filesystem --upload.outputDir=./demo/react-vite/lighthouseci
